version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    working_directory: ~/autodeloy
    steps:
      - checkout
      - run:
          name: Fix ssh Could not resolve hostname
          command: |
            ssh-keyscan 18.142.103.14 >> ~/.ssh/known_hosts # Add live server IP to known hosts.
      - add_ssh_keys:
          fingerprints:
            - "26:1c:a3:09:bd:a3:9f:0f:c7:0e:c6:47:55:c9:d6:43"
      - run:
          name: Deploy main.
          command: ssh ubuntu@18.142.103.14 'cd /var/www/html/DongTP1 && git clone git@github.com:orientalinformation/autodeloy.git'; 
      # - run: ssh ubuntu@18.142.103.14 "cd /var/www/html/DongTP1 && git pull origin main"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main