version: 2.1

orbs:
  php: circleci/php@1.1.0
jobs:
  install_packages:
    executor: php/default
    steps:
      - checkout
  build_app:
    executor: php/default
    steps:
      - checkout
      - run:
          name: Zip Source Code
          command: |
            cd ../
            zip -r Source.zip project
            ls
      - run:
          name: Login Server
          command: |
            ssh -t -o StrictHostKeyChecking=no ubuntu@18.142.103.14 "sudo rm -rf source"
            ssh -t -o StrictHostKeyChecking=no ubuntu@18.142.103.14 "mkdir -p source; sudo chmod 777 source"
      - run:
          name: Push Source Server
          command: |
            cd ../
            scp -o StrictHostKeyChecking=no -rp Source.zip ubuntu@18.142.103.14:/home/ubuntu/source
      - run:
          name: Copy Source
          command: |
            ssh -t -o StrictHostKeyChecking=no ubuntu@18.142.103.14 "cd source; sudo unzip Source.zip"
            ssh -t -o StrictHostKeyChecking=no ubuntu@18.142.103.14 "sudo mv /home/ubuntu/source/project/* /var/www/html/SonNK/"
workflows:
  version: 2.1
  auto_deploy:
    jobs:
      - install_packages
      - build_app:
         requires:
            - install_packages
         filters:
           branches:
             only: delevop